### ISSUE TITLE
More `Index` implementations

### ISSUE THREAD

**Issue by Kestrer** [Kestrer/bounded-integer#18]
With #17, it has occurred to be that it might be useful to support more implementations of `Index`. This issue tracks:

- [ ] `impl Index` for macro-generated `usize`-backed types
- [x] [not possible] Indexing with ranges on slices and `Vec`s 
- [x] [not possible] Indexing with ranges on `str`, `String`, and `CStr` (copy [the implementations in libcore](https://doc.rust-lang.org/stable/std/ops/trait.Index.html#implementors))

**Comment by O-X-E-Y** [comment]
working on getting `bounded_integer!` indexing to work, will look at string indexing after that

**Comment by O-X-E-Y** [comment]
so it seems for ranges a custom range object is needed (maybe created by some `Bounded.to(Bounded)` syntax?) because of orphaning rules. For example, if you try to `impl Index<Range<Bounded>> for [T]`, you get this error:

> only traits defined in the current crate can be implemented for arbitrary types. Define and implement a trait or new type instead
> [T] is not defined in the current crate because slices are always foreign
> std::ops::Range is not defined in the current crate

This can be circumvented by creating a `BoundedRange` struct that a function like `pub fn to(&self, b: Bounded) -> BoundedRange` returns, which unfortunately means `Bounded..Bounded` syntax isn't possible at the moment, or at least not for indexing. If you think that's a good alternative for now I can go ahead and implement it, in any case I think if proper `Range` indexing becomes available you can always mark this as deprecated

**Comment by Kestrer** [comment]
I don’t really think `BoundedRange` is worth it — if implemented, this feature’s purpose would mostly be for conveniënce, and `s[BoundedRange::new(start, end)]` isn’t exactly more conveniënt than `s[start.get()..end.get()]`. So I think I’ll leave it as-is, and check off that box.

**Comment by O-X-E-Y** [comment]
probably can close this, at least for the time being
also np on the contributions, it's a cool crate and since I never really used syn + quote before I feel like I learnt a lot haha. might revisit this if I find myself missing something but if not, gl :wave:
